//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPodder.PortaPodder
{
	
	
	public partial class Resource
	{
		
		public partial class EpisodeDetails
		{
			
			// aapt resource value: 0x7f080006
			public const int Delete = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int DetailsText = 2131230720;
			
			// aapt resource value: 0x7f080005
			public const int Download = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int Play = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int SkipBack = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int SkipForwards = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int Stop = 2131230723;
			
			// aapt resource value: 0x7f080007
			public const int Toggle = 2131230727;
			
			private EpisodeDetails()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class EpisodeArray
		{
			
			// aapt resource value: 0x7f060001
			public const int episodeText = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int subscriptionText = 2131099648;
			
			private EpisodeArray()
			{
			}
		}
		
		public partial class EpisodeList
		{
			
			// aapt resource value: 0x7f090002
			public const int episodeList = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int layout = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int loginText = 2131296257;
			
			private EpisodeList()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int Refresh = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int devices = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int relativeLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int subscription = 2131165186;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EpisodeArray = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EpisodeDetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EpisodesList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SelectDevice = 2130903043;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int devices = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int episodes = 2131034113;
			
			private Menu()
			{
			}
		}
		
		public partial class SelectDevice
		{
			
			// aapt resource value: 0x7f0a0002
			public const int deviceListView = 2131361794;
			
			// aapt resource value: 0x7f0a0000
			public const int layout = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int selectDeviceText = 2131361793;
			
			private SelectDevice()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int no_devices = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int select_devices = 2130968578;
			
			private String()
			{
			}
		}
	}
}
